// <auto-generated />
using System;
using CarShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarShop.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20250628101249_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarShop.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Riham@gmail.com",
                            Name = "Riham",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Hamsa@gmail.com",
                            Name = "Hamsa",
                            Password = "5678"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Areen@gmail.com",
                            Name = "Areen",
                            Password = "9123"
                        });
                });

            modelBuilder.Entity("CarShop.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"), 1L, 1);

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Make = "Mercedec",
                            Model = "G_CLASS",
                            Price = 500000m,
                            Year = 2013
                        },
                        new
                        {
                            CarId = 2,
                            Make = "Mercedec",
                            Model = "G_CLASS",
                            Price = 500000m,
                            Year = 2013
                        },
                        new
                        {
                            CarId = 3,
                            Make = "Mercedec",
                            Model = "G_CLASS",
                            Price = 500000m,
                            Year = 2013
                        },
                        new
                        {
                            CarId = 4,
                            Make = "Mercedec",
                            Model = "G_CLASS",
                            Price = 500000m,
                            Year = 2013
                        });
                });

            modelBuilder.Entity("CarShop.Models.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CarId");

                    b.ToTable("Repositories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionDate = new DateTime(2025, 6, 28, 13, 12, 49, 398, DateTimeKind.Local).AddTicks(7956),
                            AdminId = 1,
                            CarId = 1,
                            Make = "Mercedece"
                        },
                        new
                        {
                            Id = 2,
                            ActionDate = new DateTime(2025, 6, 28, 13, 12, 49, 398, DateTimeKind.Local).AddTicks(7993),
                            AdminId = 2,
                            CarId = 2,
                            Make = "Mercedece"
                        },
                        new
                        {
                            Id = 3,
                            ActionDate = new DateTime(2025, 6, 28, 13, 12, 49, 398, DateTimeKind.Local).AddTicks(7996),
                            AdminId = 3,
                            CarId = 3,
                            Make = "Mercedece"
                        });
                });

            modelBuilder.Entity("CarShop.Models.Repository", b =>
                {
                    b.HasOne("CarShop.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarShop.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
